objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line1__c</fullName>
        <label>Address Line1</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line2__c</fullName>
        <label>Address Line2</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Best_Time_to_Call__c</fullName>
        <label>Best Time to Call</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Early afternoon</fullName>
                </value>
                <value>
                    <fullName>Early morning</fullName>
                </value>
                <value>
                    <fullName>Evening</fullName>
                </value>
                <value>
                    <fullName>Late afternoon</fullName>
                </value>
                <value>
                    <fullName>Mid-morning</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Weekend</fullName>
                </value>
                <value>
                    <fullName>Any Time</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Trans</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Languages__c</fullName>
        <label>Languages</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>All Patient records require this field</inlineHelpText>
        <label>Patient</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reg_Id__c</fullName>
        <description>It&apos;s unique id for each patient</description>
        <displayFormat>1-{000000000}</displayFormat>
        <label>Reg Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Temporary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Family Doctor</fullName>
                </value>
                <value>
                    <fullName>Insurance Rep</fullName>
                </value>
                <value>
                    <fullName>MD Specialist</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Nurse Practitioner</fullName>
                </value>
                <value>
                    <fullName>Pharmacist</fullName>
                </value>
                <value>
                    <fullName>Physician</fullName>
                </value>
                <value>
                    <fullName>Physiotherapist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UpdateContactService.cls
@RestResource (urlMapping='/UpdateContactService/*')
global class UpdateContactService {
public class Contactslistobj{

    public Contactslist Contactslistobj;
}   
public class Contactslist{
public List<Contactcls> Contactslist;
}
public class Contactcls {
        public String Id{ get; set; }
        public String FirstName{ get; set; }
        public String LastName{ get; set; }
        public Addresseslst Addresseslstobj;
    						}
    public class Addresseslst{
        public List<Address> Addresseslst;
    }
    public class Address{
        public String Id{ get; set; }
        public String Addline1{ get; set; }
		public String Addline2{ get; set; }
    }
    Global class Response
    {
    public String message;
    public String exception_msg;
  }
@httppatch
    Global static Response UpdtConSer()
    {
        RestRequest request = RestContext.request;
        Response response = new Response();
        //Map<String, Object> Param = (Map<String, Object>)JSON.deserialize(request.requestBody.toString(), Contactscls.class);
        //Contactscls ccls = JSON.deserialize(Param, Contactscls.class);
        //system.debug('Values'+Param);
        Contactslistobj cons = new Contactslistobj();
        cons = (Contactslistobj)System.JSON.deserialize(request.requestBody.toString(), Contactslistobj.class);
       // System.debug('Respone- ' + cons);
       // System.debug('Respone-Add Id ' + cons.Contactslistobj.Contactslist.get(0).Addresseslstobj.Addresseslst.get(0).Id);
        String IDS = 'Success';
        try{
        //cons.Contactslistobj.Contactslist.get(0).Addresseslstobj.Addresseslst.get(0).Id;
        Integer i = cons.Contactslistobj.Contactslist.size();
        for(Integer j=0; j<i; j++)
        {
            String st = cons.Contactslistobj.Contactslist.get(j).Id;
            Contact cos = [select Id, FirstName, LastName, MailingAddress, MobilePhone, Email, Phone, Birthdate, Reg_Id__c, Gender__c, Languages__c, Patient__c, Status__c, Best_Time_to_Call__c, Type__c from Contact where Id=:st limit 1];
            cos.FirstName = cons.Contactslistobj.Contactslist.get(j).FirstName;
            cos.LastName = cons.Contactslistobj.Contactslist.get(j).LastName;
            Integer x = cons.Contactslistobj.Contactslist.get(j).Addresseslstobj.Addresseslst.size();
            for(integer l=0; l<x ; l++)
            {
                String sp = cons.Contactslistobj.Contactslist.get(j).Addresseslstobj.Addresseslst.get(l).Id;
                Address__C A = [SELECT Id, Address_Line1__c, Address_Line2__c  FROM Address__c where Id =:sp];
                A.Address_Line1__c = cons.Contactslistobj.Contactslist.get(j).Addresseslstobj.Addresseslst.get(l).Addline1;
                A.Address_Line2__c = cons.Contactslistobj.Contactslist.get(j).Addresseslstobj.Addresseslst.get(l).Addline2;
                update A;
            }
            update cos;
        }
        }catch(Exception e) {
          response.message = 'Failed';
          response.exception_msg = e.getMessage();         
          return response;
            //return IDS;
      }
        response.message = 'Successful';
        response.exception_msg = Null;
        return response;
    }  
}