objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Address_Line1__c</fullName>
        <label>Address Line1</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line2__c</fullName>
        <label>Address Line2</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line3__c</fullName>
        <label>Address Line3</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provience__c</fullName>
        <label>Province</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Best_Time_to_Call__c</fullName>
        <label>Best Time to Call</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Early afternoon</fullName>
                </value>
                <value>
                    <fullName>Early morning</fullName>
                </value>
                <value>
                    <fullName>Evening</fullName>
                </value>
                <value>
                    <fullName>Late afternoon</fullName>
                </value>
                <value>
                    <fullName>Mid-morning</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Weekend</fullName>
                </value>
                <value>
                    <fullName>Any Time</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Trans</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Languages__c</fullName>
        <label>Languages</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>All Patient records require this field</inlineHelpText>
        <label>Patient</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reg_Id__c</fullName>
        <description>It&apos;s unique id for each patient</description>
        <displayFormat>1-{000000000}</displayFormat>
        <label>Reg Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Temporary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Family Doctor</fullName>
                </value>
                <value>
                    <fullName>Insurance Rep</fullName>
                </value>
                <value>
                    <fullName>MD Specialist</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Nurse Practitioner</fullName>
                </value>
                <value>
                    <fullName>Pharmacist</fullName>
                </value>
                <value>
                    <fullName>Physician</fullName>
                </value>
                <value>
                    <fullName>Physiotherapist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact_Addresses__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipName>Contact_Addresses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Contact_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Address</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Contact_Addresses Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/GetContactDetails.cls
@RestResource (urlMapping='/GetContactDetails/*')
Global class GetContactDetails {
    
public class ConAddresses {
public Contact Con;
public List<Address__c> Addresses;
    public ConAddresses(Contact co, List <Address__c> LL)
    {
        Con = co;
        Addresses = LL;
    }
}
    
@httpget
    Global static String GetConDetails()
    {
        RestRequest request = RestContext.request;
        String st = request.requestURI.substring(request.requestURI.LastIndexof('/')+1);
		List<Contact> c1 = [select Id, FirstName, LastName, MailingAddress, MobilePhone, Email, Phone, Birthdate, Reg_Id__c, Gender__c, Languages__c, Patient__c, Status__c, Best_Time_to_Call__c, Type__c from Contact where Id=:st limit 1];
		List<Address__c> LA = new List<Address__c>();
integer j = 0;
for (Contact C: c1)
{
    String stp = c1.get(j).Id;
    List <Contact_Addresses__c> ConAdd = [SELECT Id,Name, Address__c, Contact__c FROM Contact_Addresses__c where Contact__c=:stp]; 
    Integer i = 0; 
      for(Contact_Addresses__c CA: ConAdd){
            String st1=ConAdd.get(i).Address__c;
            Address__c AC =[select Id, Active__c, Address_Line1__c, Address_Line2__c, Address_Line3__c, City__c, Country__c, Postal_Code__c, Provience__c from  Address__c where Id=:st1];
          LA.add(Ac);
          
          i++;
          
        }

    j++;
} 
     
        ConAddresses Cads = new ConAddresses(c1.get(0), LA);
		        return json.serialize(Cads);
        
  
    }
}