objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Trans</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>All Patient records require this field</inlineHelpText>
        <label>Patient</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Family Doctor</fullName>
                </value>
                <value>
                    <fullName>Insurance Rep</fullName>
                </value>
                <value>
                    <fullName>MD Specialist</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Nurse Practitioner</fullName>
                </value>
                <value>
                    <fullName>Pharmacist</fullName>
                </value>
                <value>
                    <fullName>Physician</fullName>
                </value>
                <value>
                    <fullName>Physiotherapist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Contest.cls
@isTest
public class Contest {
    @isTest static void test1() {
        Contact C1 = new Contact(Lastname = 'pks', FirstName='Fname',  RecordTypeId = '0123i000000YhM6AAK', Patient__c=true, Gender__c ='Male', Type__c = 'None', Phone ='4162099876');
        Test.startTest();
        // Call method to publish events
        insert c1;
        Test.stopTest();
        // Perform validation here
        Contact con = [SELECT Id, Description FROM Contact where Lastname = 'pks' limit 1];
        // Validate that this case was found.
        // There is only one test case in test context.
        System.assertEquals('NRK portal contact:Insert', con.Description);
        
    }
}