objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Best_Time_to_Call__c</fullName>
        <label>Best Time to Call</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Early afternoon</fullName>
                </value>
                <value>
                    <fullName>Early morning</fullName>
                </value>
                <value>
                    <fullName>Evening</fullName>
                </value>
                <value>
                    <fullName>Late afternoon</fullName>
                </value>
                <value>
                    <fullName>Mid-morning</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Weekend</fullName>
                </value>
                <value>
                    <fullName>Any Time</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Trans</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Languages__c</fullName>
        <label>Languages</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>All Patient records require this field</inlineHelpText>
        <label>Patient</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reg_Id__c</fullName>
        <description>It&apos;s unique id for each patient</description>
        <displayFormat>1-{000000000}</displayFormat>
        <label>Reg Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Temporary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Family Doctor</fullName>
                </value>
                <value>
                    <fullName>Insurance Rep</fullName>
                </value>
                <value>
                    <fullName>MD Specialist</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Nurse Practitioner</fullName>
                </value>
                <value>
                    <fullName>Pharmacist</fullName>
                </value>
                <value>
                    <fullName>Physician</fullName>
                </value>
                <value>
                    <fullName>Physiotherapist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/jsonparsingtest.cls
public class jsonparsingtest{

    public Contactslistobj getdatatest(){
        Contactslistobj cons = new Contactslistobj();
        String jsonstring = '{"Contactslistobj" :{"Contactslist":[' +
            '{"Id" : "0033i000007UsxeAAC","FirstName" : "Raja","LastName" : "mouli", "Addresseslstobj" : {"Addresseslst":[{"Id":"a063i000000QW8d","Addline1":"840 Dundas St E", "Addline2":"300 unit"}]}'+
            '}]}}';
        cons = (Contactslistobj)System.JSON.deserialize(jsonstring, Contactslistobj.class);
        System.debug('Respone- ' + cons);
        System.debug('Respone-Con ' + cons.Contactslistobj.Contactslist.get(0).Id);
        System.debug('Respone-Add Id ' + cons.Contactslistobj.Contactslist.get(0).Addresseslstobj.Addresseslst.get(0).Id);
        System.debug('Respone-Con ' + cons.Contactslistobj.Contactslist.size());
        System.debug('Respone-Conadd ' + cons.Contactslistobj.Contactslist.get(0).Addresseslstobj.Addresseslst.size());
        System.debug('Respone-Add Id ' + cons.Contactslistobj.Contactslist.get(0).Addresseslstobj.Addresseslst.get(0).Addline1);
        Integer i = cons.Contactslistobj.Contactslist.size();
        for(Integer j=0; j<i; j++)
        {
            String st = cons.Contactslistobj.Contactslist.get(j).Id;
            Contact cos = [select Id, FirstName, LastName, MailingAddress, MobilePhone, Email, Phone, Birthdate, Reg_Id__c, Gender__c, Languages__c, Patient__c, Status__c, Best_Time_to_Call__c, Type__c from Contact where Id=:st limit 1];
            system.debug('cos:' +cos);
        }
        return cons;
    }
public class Contactslistobj{

    public Contactslist Contactslistobj;
}   
public class Contactslist{
public List<Contactcls> Contactslist;
}
public class Contactcls {
        public String Id{ get; set; }
        public String FirstName{ get; set; }
        public String LastName{ get; set; }
        public Addresseslst Addresseslstobj;
    						}
    public class Addresseslst{
        public List<Address> Addresseslst;
    }
    public class Address{
        public String Id{ get; set; }
        public String Addline1{ get; set; }
		public String Addline2{ get; set; }
    }

}